export const termsBody = `<header class="pg-hero">
  <span class="hero-kicker">Store policies</span>
  <h1>Terms &amp; <span class="accent">conditions</span></h1>
  <p>The simple rules for ordering from MyChromebook.pk — payment, delivery, warranty and your account.</p>
</header>
<main class="pg">
  <div class="lg">
    <nav class="lg-toc" aria-label="On this page"><b>On this page</b><a href="#about">About these terms</a><a href="#orders">Placing an order</a><a href="#prices">Prices and availability</a><a href="#payment">Payment</a><a href="#delivery">Delivery</a><a href="#warranty">Warranty</a><a href="#accounts">Your account</a><a href="#privacy">Your information</a><a href="#changes">Changes to these terms</a>
      <a href="/refund" style="margin-top:8px;border-top:1px solid var(--silver-2);border-radius:0;padding-top:12px">Refund &amp; returns policy →</a></nav>
    <article class="lg-body">
      <p class="upd">Last updated: September 2026</p>
      <section id="about"><h2>About these terms</h2><p>These terms apply to every order placed on MyChromebook.pk, a venture of Tech Valley, Islamabad. By placing an order you confirm that you have read and accept them.</p></section><section id="orders"><h2>Placing an order</h2><p>When you place an order you receive an order number and a confirmation page. Your order is reserved for you, and becomes confirmed once your payment has been verified.</p><p>We may contact you on the phone number or email you provide to confirm details before dispatch.</p></section><section id="prices"><h2>Prices and availability</h2><p>All prices are shown in Pakistani Rupees (PKR) and include applicable taxes. Prices and stock can change without notice, but the price shown when you place your order is the price you pay.</p><p>If a product becomes unavailable after you order, we will contact you and offer an alternative or a full refund.</p></section><section id="payment"><h2>Payment</h2><p>At present we accept direct bank transfer. After placing your order, transfer the order total to the account shown on your confirmation page and send the payment screenshot to us on WhatsApp with your order number.</p><p>Your order status shows <b>Awaiting payment verification</b> until our team confirms the transfer. Orders that are not paid within 48 hours may be cancelled, and we will let you know before doing so.</p></section><section id="delivery"><h2>Delivery</h2><p>Delivery is free anywhere in Pakistan. Orders are usually delivered within 3–5 working days after payment is verified. Delivery times to remote areas may be longer.</p><p>Please check your parcel on arrival. If it looks damaged, let us know on WhatsApp within 24 hours with a photo.</p></section><section id="warranty"><h2>Warranty</h2><p>Every device we sell is genuine. New Chromebooks carry the official warranty stated on the product page, and certified refurbished devices carry the warranty stated on their product page. Warranty does not cover accidental damage, liquid damage or unauthorised repairs.</p></section><section id="accounts"><h2>Your account</h2><p>You can check out as a guest or create an account. You are responsible for keeping your password private. Please tell us straight away if you think someone else has used your account.</p></section><section id="privacy"><h2>Your information</h2><p>We use the details you give us only to process and deliver your order, to provide support, and — if you agree — to send you updates. We do not sell your information to anyone.</p></section><section id="changes"><h2>Changes to these terms</h2><p>We may update these terms from time to time. The version shown on this page on the day you place your order is the one that applies to that order.</p></section>
      <div class="lg-help"><p>Questions about an order, a return or a warranty claim? Our team is happy to help.</p>
        <a class="btn btn-rose" href="/contact">Contact us <span class="arrow-c">↗</span></a></div>
    </article>
  </div>
</main>`;
